-- ============================================================================
-- Create ACH_FILES_BLOBS Table
-- ============================================================================
-- This table stores file contents as BLOB/CLOB for ACH files processed
-- from the SFTP server. The table structure mirrors ACH_FILES but uses
-- FILE_BLOB_ID as the primary key.
--
-- Created: 2025-11-09
-- ============================================================================

CREATE TABLE "ACH_FILES_BLOBS"
(
    "FILE_BLOB_ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY 
        MINVALUE 1 
        MAXVALUE 9999999999999999999999999999 
        INCREMENT BY 1 
        START WITH 1 
        CACHE 20 
        NOORDER 
        NOCYCLE 
        NOKEEP 
        NOSCALE 
        NOT NULL 
        ENABLE,
    "FILE_ID" NUMBER(38,0) NOT NULL ENABLE,
    "ORIGINAL_FILENAME" VARCHAR2(255) NOT NULL ENABLE,
    "PROCESSING_STATUS" VARCHAR2(50) DEFAULT 'Pending' NOT NULL ENABLE,
    "FILE_CONTENTS" CLOB,
    "CREATED_BY_USER" VARCHAR2(50) DEFAULT 'system-user' NOT NULL ENABLE,
    "CREATED_DATE" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE,
    "UPDATED_BY_USER" VARCHAR2(50),
    "UPDATED_DATE" TIMESTAMP(6),
    CONSTRAINT "PK_ACH_FILES_BLOBS" PRIMARY KEY ("FILE_BLOB_ID") 
        USING INDEX ENABLE
);

-- ============================================================================
-- Add Foreign Key Constraint to ACH_FILES
-- ============================================================================

ALTER TABLE "ACH_FILES_BLOBS" 
ADD CONSTRAINT "FK_ACH_FILES_BLOBS_FILE_ID" 
FOREIGN KEY ("FILE_ID") 
REFERENCES "ACH_FILES" ("FILE_ID") 
ON DELETE CASCADE 
ENABLE;

-- ============================================================================
-- Create Index on FILE_ID for faster joins with ACH_FILES
-- ============================================================================

CREATE INDEX "IDX_ACH_FILES_BLOBS_FILE_ID" 
ON "ACH_FILES_BLOBS" ("FILE_ID");

-- ============================================================================
-- Create Index on ORIGINAL_FILENAME for faster lookups
-- ============================================================================

CREATE INDEX "IDX_ACH_FILES_BLOBS_FILENAME" 
ON "ACH_FILES_BLOBS" ("ORIGINAL_FILENAME");

-- ============================================================================
-- Create Index on PROCESSING_STATUS for filtering queries
-- ============================================================================

CREATE INDEX "IDX_ACH_FILES_BLOBS_STATUS" 
ON "ACH_FILES_BLOBS" ("PROCESSING_STATUS");

-- ============================================================================
-- Create Index on CREATED_DATE for sorting and date range queries
-- ============================================================================

CREATE INDEX "IDX_ACH_FILES_BLOBS_CREATED_DATE" 
ON "ACH_FILES_BLOBS" ("CREATED_DATE");

-- ============================================================================
-- Add Comments to Table and Columns
-- ============================================================================

COMMENT ON TABLE "ACH_FILES_BLOBS" IS 'Stores file contents as CLOB for ACH files processed from SFTP server';
COMMENT ON COLUMN "ACH_FILES_BLOBS"."FILE_BLOB_ID" IS 'Primary key - auto-incrementing identifier';
COMMENT ON COLUMN "ACH_FILES_BLOBS"."FILE_ID" IS 'Foreign key to ACH_FILES.FILE_ID';
COMMENT ON COLUMN "ACH_FILES_BLOBS"."ORIGINAL_FILENAME" IS 'Original filename from SFTP server (may include CLIENTID prefix)';
COMMENT ON COLUMN "ACH_FILES_BLOBS"."PROCESSING_STATUS" IS 'Processing status: Pending, Completed, Failed';
COMMENT ON COLUMN "ACH_FILES_BLOBS"."FILE_CONTENTS" IS 'File contents stored as CLOB';
COMMENT ON COLUMN "ACH_FILES_BLOBS"."CREATED_BY_USER" IS 'User who created the record';
COMMENT ON COLUMN "ACH_FILES_BLOBS"."CREATED_DATE" IS 'Timestamp when record was created';
COMMENT ON COLUMN "ACH_FILES_BLOBS"."UPDATED_BY_USER" IS 'User who last updated the record';
COMMENT ON COLUMN "ACH_FILES_BLOBS"."UPDATED_DATE" IS 'Timestamp when record was last updated';

-- ============================================================================
-- Verification Queries
-- ============================================================================
-- Uncomment and run these queries to verify the table was created correctly:
--
-- SELECT table_name, num_rows 
-- FROM user_tables 
-- WHERE table_name = 'ACH_FILES_BLOBS';
--
-- SELECT column_name, data_type, data_length, nullable, data_default
-- FROM user_tab_columns
-- WHERE table_name = 'ACH_FILES_BLOBS'
-- ORDER BY column_id;
--
-- SELECT index_name, index_type, uniqueness
-- FROM user_indexes
-- WHERE table_name = 'ACH_FILES_BLOBS';

